"""Sandbox service constants."""

from pathlib import Path


TASK_QUEUE = "json-control-flow-visualization-task-queue"
WORKFLOW_LIST_QUERY = 'WorkflowType = "JsonDagWorkflow"'
WORKFLOW_LIST_LIMIT = 200
WORKFLOW_QUERY_TIMEOUT_SECONDS = 3
WORKFLOW_RESULT_TIMEOUT_SECONDS = 3
COMPLETED_WORKFLOW_DISPLAY_LIMIT = 10
API_RESULT_TEXT_LIMIT = 1200
API_RESULT_LIST_LIMIT = 3
DEFAULT_TEMPORAL_HOST = "127.0.0.1"
DEFAULT_TEMPORAL_PORT = 7233
DEFAULT_TEMPORAL_UI_PORT = 8233
DEFAULT_TEMPORAL_DB_FILE = Path("D:/dev/MAOS/temporal-data/temporal.db")
